"""Checks payload.py against src/dataCode.vectors.json, the overlay's own output.

payload.py and src/dataCode.ts are separate implementations of one wire format. This test
is what stops them drifting: the vectors are generated by the TypeScript side, so if either
the field table or the bit packing diverges, this fails.

    python highlights/test_payload.py       # standalone
    pytest highlights/test_payload.py       # or under pytest
"""
from __future__ import annotations
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from payload import FIELDS, PAYLOAD_BYTES, pack, unpack, crc16, NAME_CHARS

VECTORS = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "..", "src", "dataCode.vectors.json")


def _load():
    with open(VECTORS) as fh:
        return json.load(fh)


def test_field_table_matches_the_overlay():
    """The table is written out independently in each language; they must agree exactly."""
    doc = _load()
    theirs = [(f["key"], f["bits"], f["kind"]) for f in doc["fields"]]
    assert FIELDS == theirs, (
        "field table drifted from src/dataCode.ts\n"
        f"  python: {FIELDS}\n  overlay: {theirs}")


def test_payload_is_42_bytes():
    """43 would tip the QR from version 3 to version 4, 148px to 164px at 4px modules."""
    doc = _load()
    assert PAYLOAD_BYTES == doc["payloadBytes"] == 42


def test_packs_byte_for_byte_like_the_overlay():
    for v in _load()["vectors"]:
        got = pack(v["fields"])
        want = bytes(v["bytes"])
        assert got == want, (
            f"vector {v['name']}: packing differs from the overlay\n"
            f"  python:  {list(got)}\n  overlay: {list(want)}")


def test_unpacks_the_overlay_bytes_back_to_the_same_fields():
    for v in _load()["vectors"]:
        fields, ok = unpack(bytes(v["bytes"]))
        assert ok, f"vector {v['name']}: CRC failed on bytes the overlay produced"
        for key, want in v["fields"].items():
            assert fields[key] == want, (
                f"vector {v['name']}, field {key}: got {fields[key]!r}, want {want!r}")


def test_crc_rejects_a_flipped_bit():
    data = bytearray(_load()["vectors"][0]["bytes"])
    for i in range(0, PAYLOAD_BYTES * 8, 7):
        bad = bytearray(data)
        bad[i >> 3] ^= 0x80 >> (i & 7)
        _, ok = unpack(bytes(bad))
        assert not ok, f"a bit flip at {i} slipped past the CRC"


def test_crc16_standard_check_vector():
    bits = []
    for ch in b"123456789":
        bits += [(ch >> i) & 1 for i in range(7, -1, -1)]
    assert crc16(bits) == 0x29B1


def test_names_hold_the_width_the_bar_displays():
    assert NAME_CHARS == 18
    long = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    fields, ok = unpack(pack({"strikerName": long}))
    assert ok and fields["strikerName"] == long[:18]


if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    failed = 0
    for fn in fns:
        try:
            fn()
            print(f"  PASS  {fn.__name__}")
        except AssertionError as e:
            failed += 1
            print(f"  FAIL  {fn.__name__}\n        {e}")
        except Exception as e:
            # a width change can make unpack run off the end; report it, do not crash out
            failed += 1
            print(f"  ERROR {fn.__name__}\n        {type(e).__name__}: {e}")
    print(f"\n{len(fns) - failed}/{len(fns)} passed")
    sys.exit(1 if failed else 0)
