import { CricketAPIData } from './types';

export const sampleReplayData: CricketAPIData[] = [
    {
        "values": {
            "seriesName": "TopGuns Premier League",
            "matchId": "12345",
            "result": "",
            "isMatchEnded": "0",
            "isSecondInningsStarted": "false",
            "t1Name": "India",
            "t1Code": "IND",
            "t1Total": "20",
            "t1Wickets": "0",
            "t1Overs": "2.1",
            "t2Name": "Australia",
            "t2Code": "AUS",
            "t2Total": "0",
            "t2Wickets": "0",
            "t2Overs": "0.0",
            "batsman1Name": "V. Kohli",
            "batsman1Runs": "12",
            "batsman1Balls": "8",
            "batsman1Fours": "1",
            "batsman1Sixers": "0",
            "batsman2Name": "R. Sharma",
            "batsman2Runs": "8",
            "batsman2Balls": "5",
            "batsman2Fours": "1",
            "batsman2Sixers": "0",
            "bowlerName": "J. Bumrah",
            "bowlerWickets": "0",
            "bowlerRuns": "10",
            "bowlerOvers": "1.1",
            "bowlerMaidens": "0",
            "firstLogo": "/images/team1_logo.png",
            "secondLogo": "/images/team2_logo.png"
        },
        "balls": ["1"]
    },
    {
        "values": {
            "seriesName": "TopGuns Premier League",
            "matchId": "12345",
            "result": "",
            "isMatchEnded": "0",
            "isSecondInningsStarted": "false",
            "t1Name": "India",
            "t1Code": "IND",
            "t1Total": "24",
            "t1Wickets": "0",
            "t1Overs": "2.2",
            "t2Name": "Australia",
            "t2Code": "AUS",
            "t2Total": "0",
            "t2Wickets": "0",
            "t2Overs": "0.0",
            "batsman1Name": "V. Kohli",
            "batsman1Runs": "12",
            "batsman1Balls": "8",
            "batsman1Fours": "1",
            "batsman1Sixers": "0",
            "batsman2Name": "R. Sharma",
            "batsman2Runs": "12",
            "batsman2Balls": "6",
            "batsman2Fours": "2",
            "batsman2Sixers": "0",
            "bowlerName": "J. Bumrah",
            "bowlerWickets": "0",
            "bowlerRuns": "14",
            "bowlerOvers": "1.2",
            "bowlerMaidens": "0",
            "firstLogo": "/images/team1_logo.png",
            "secondLogo": "/images/team2_logo.png"
        },
        "balls": ["1", "4"]
    },
    {
        "values": {
            "seriesName": "TopGuns Premier League",
            "matchId": "12345",
            "result": "",
            "isMatchEnded": "0",
            "isSecondInningsStarted": "false",
            "t1Name": "India",
            "t1Code": "IND",
            "t1Total": "25",
            "t1Wickets": "0",
            "t1Overs": "2.2",
            "t2Name": "Australia",
            "t2Code": "AUS",
            "t2Total": "0",
            "t2Wickets": "0",
            "t2Overs": "0.0",
            "batsman1Name": "V. Kohli",
            "batsman1Runs": "12",
            "batsman1Balls": "8",
            "batsman1Fours": "1",
            "batsman1Sixers": "0",
            "batsman2Name": "R. Sharma",
            "batsman2Runs": "12",
            "batsman2Balls": "6",
            "batsman2Fours": "2",
            "batsman2Sixers": "0",
            "bowlerName": "J. Bumrah",
            "bowlerWickets": "0",
            "bowlerRuns": "15",
            "bowlerOvers": "1.2",
            "bowlerMaidens": "0",
            "firstLogo": "/images/team1_logo.png",
            "secondLogo": "/images/team2_logo.png"
        },
        "balls": ["1", "4", "1wd"]
    },
    {
        "values": {
            "seriesName": "TopGuns Premier League",
            "matchId": "12345",
            "result": "",
            "isMatchEnded": "0",
            "isSecondInningsStarted": "false",
            "t1Name": "India",
            "t1Code": "IND",
            "t1Total": "31",
            "t1Wickets": "0",
            "t1Overs": "2.3",
            "t2Name": "Australia",
            "t2Code": "AUS",
            "t2Total": "0",
            "t2Wickets": "0",
            "t2Overs": "0.0",
            "batsman1Name": "V. Kohli",
            "batsman1Runs": "12",
            "batsman1Balls": "8",
            "batsman1Fours": "1",
            "batsman1Sixers": "0",
            "batsman2Name": "R. Sharma",
            "batsman2Runs": "18",
            "batsman2Balls": "7",
            "batsman2Fours": "2",
            "batsman2Sixers": "1",
            "bowlerName": "J. Bumrah",
            "bowlerWickets": "0",
            "bowlerRuns": "21",
            "bowlerOvers": "1.3",
            "bowlerMaidens": "0",
            "firstLogo": "/images/team1_logo.png",
            "secondLogo": "/images/team2_logo.png"
        },
        "balls": ["1", "4", "1wd", "6"]
    },
    {
        "values": {
            "seriesName": "TopGuns Premier League",
            "matchId": "12345",
            "result": "",
            "isMatchEnded": "0",
            "isSecondInningsStarted": "false",
            "t1Name": "India",
            "t1Code": "IND",
            "t1Total": "31",
            "t1Wickets": "1",
            "t1Overs": "2.4",
            "t2Name": "Australia",
            "t2Code": "AUS",
            "t2Total": "0",
            "t2Wickets": "0",
            "t2Overs": "0.0",
            "batsman1Name": "V. Kohli",
            "batsman1Runs": "12",
            "batsman1Balls": "8",
            "batsman1Fours": "1",
            "batsman1Sixers": "0",
            "batsman2Name": "R. Sharma",
            "batsman2Runs": "18",
            "batsman2Balls": "8",
            "batsman2Fours": "2",
            "batsman2Sixers": "1",
            "bowlerName": "J. Bumrah",
            "bowlerWickets": "1",
            "bowlerRuns": "21",
            "bowlerOvers": "1.4",
            "bowlerMaidens": "0",
            "firstLogo": "/images/team1_logo.png",
            "secondLogo": "/images/team2_logo.png"
        },
        "balls": ["1", "4", "1wd", "6", "W"]
    }
];
